### ISSUE TITLE
SessionManagerLayer type error after upgrading to 5.0

### ISSUE THREAD

**Issue by muxcmux** [maxcountryman/tower-sessions#88]
Hello

First of all - Thanks for your work on that crate!

I just updated to the latest release (0.5.0) and I keep getting this missmatched types compiler error "expected `SessionManagerLayer<_>`, found `SessionManagerLayer<MemoryStore>`".

My program works with 0.4.3 version of tower-sessions. I'm new to Rust and thought I was doing something wrong when instantiating a session, but then I tried the example and it yields the same error when bumping to 0.5.0.

```
error[E0308]: mismatched types
   --> examples/sqlite/src/web/app.rs:49:51
    |
49  |             .layer(AuthManagerLayer::new(backend, session_layer));
    |                    ---------------------          ^^^^^^^^^^^^^ expected `SessionManagerLayer<_>`, found `SessionManagerLayer<MemoryStore>`
```

Any pointers to where I should look to resolve that error are much appreciated.

Thanks!

**Comment by maxcountryman** [comment]
Hi thanks for mentioning this--I just tried to reproduce, but haven't been able to so far. For instance, I tried with the `sqlite` example:

```
$ cargo run --example sqlite-store --features="axum-core sqlite-store deletion-task"
```

It's possible there's some caching here that's either masking a problem or otherwise creating a problem. Have you tried running `cargo clean` before executing the problem? This might help bust a stale cache.

I'm also looking more closer at the error message you shared: `examples/sqlite/src/web/app.rs:49:51` looks like a path of our `axum-login` example. Am I right in guessing you're running into this with `axum-login`? If so, this is expected: we haven't update `axum-login` with `tower-sessions` 0.5.0 just yet (but will plan to do so shortly).

**Comment by muxcmux** [comment]
Yes, you are absolutely spot on - sorry, I should have mentioned this and given some more context. I am in fact using `axum-login` and also `tower-sessions` via the re-export. The example I ran is from `axum-login` here: https://github.com/maxcountryman/axum-login/tree/main/examples/sqlite

I simply cd-ed into the example directory and ran `cargo run`, which is probably not the right thing to do, although it does work fine with `tower-sessions` set to 0.4.1 and I am able to run the example and go through tye whole log-in process in the browser.

I just tried `cargo clean` as you suggested, but that doesn't seem to resolve the error.

**Comment by maxcountryman** [comment]
In that case, you'll want to keep your project at 0.4.x until we update `axum-login` with `tower-sessions` 0.5.x.

**Comment by muxcmux** [comment]
Yes, that's what I've done for the moment being, but opened this issue as I wasn't sure if this was me doing something wrong, or a genuine incompatibility. I'll close that issue, as it seems to be related to `axum-login` rather than `tower-sessions`.

Thank you.
