### ISSUE TITLE
Breaking change in v0.10.4

### ISSUE THREAD

**Issue by ciffelia** [maxcountryman/tower-sessions#162]
- [x] I have looked for existing issues (including closed) about this

### Version

```toml
tower-sessions = "=0.10.4"
```

### Platform

```
Linux a1fc3b8591b7 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 GNU/Linux
```

### Crates

tower-sessions

### Description

The following code compiles with tower-sessions 0.10.2 but not with 0.10.4. It might be related to #160.

```rust
use tower_sessions::{MemoryStore, SessionManagerLayer};

fn create_layer(cookie_name: String) -> SessionManagerLayer<MemoryStore> {
    let session_store = MemoryStore::default();
    SessionManagerLayer::new(session_store).with_name(&cookie_name)
}

fn main() {
    create_layer("cookie_foo".to_string());
}
```

```rust
error[E0597]: `cookie_name` does not live long enough
 --> src/main.rs:5:55
  |
3 | fn create_layer(cookie_name: String) -> SessionManagerLayer<MemoryStore> {
  |                 ----------- binding `cookie_name` declared here
4 |     let session_store = MemoryStore::default();
5 |     SessionManagerLayer::new(session_store).with_name(&cookie_name)
  |     --------------------------------------------------^^^^^^^^^^^^-
  |     |                                                 |
  |     |                                                 borrowed value does not live long enough
  |     argument requires that `cookie_name` is borrowed for `'static`
6 | }
  | - `cookie_name` dropped here while still borrowed
```

**Comment by maxcountryman** [comment]
Unfortunately the reason this worked before is because the method allocated via `to_string` internally (not so great obviously). The changes in 0.10.4 make it so either a stack or heap allocated value may be used and indeed a `&str` may be used here. It seems the issue you're running into is that 0.10.4 made the lifetime static. Ultimately we do want the config to be static because we don't want to allocate for what is a constant set of values over the lifetime of the program. Needless to say we do not want to break SemVer (altho it's not clear how to avoid that given the prior release also broke SemVer).

**Comment by ciffelia** [comment]
IMHO it's impossible to make the config static without requiring the argument of `with_name` to be static.

**Comment by maxcountryman** [comment]
I agree. That means we can yank 0.10.4 and republish as 0.11. I don't think there's much else that can be done. If there's a larger problem with that API, with your specific use case, please let me know.

**Comment by maxcountryman** [comment]
This is resolved via yanking `0.10.4` and publishing `0.11.0`. Thanks for reporting it!
