### ISSUE TITLE
2 Errors when installing with postgres

### ISSUE THREAD

**Issue by HosMercury** [maxcountryman/tower-sessions#109]
`    let session_store = PostgresStore::new(pool);
    session_store.migrate().await.unwrap();

    let deletion_task = tokio::task::spawn(
        session_store
            .clone()
            .continuously_delete_expired(tokio::time::Duration::from_secs(60)),
    );

    let session_service = ServiceBuilder::new()
        .layer(HandleErrorLayer::new(|_: BoxError| async {
            StatusCode::BAD_REQUEST
        }))
        .layer(
            SessionManagerLayer::new(session_store)
                .with_secure(false)
                .with_expiry(Expiry::OnInactivity(Duration::seconds(10))),
        );

    let app = routes::web().layer(session_service).with_state(state);`
    
    I have 2 errs 
    
```

    error[E0599]: no method named `continuously_delete_expired` found for struct `PostgresStore` in the current scope
  --> src/lib.rs:87:14
   |
85 | /         session_store
86 | |             .clone()
87 | |             .continuously_delete_expired(tokio::time::Duration::from...
   | |             -^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `PostgresStore`
   | |_____________|
   |

error[E0277]: the trait bound `HandleError<tower_cookies::service::CookieManager<SessionManager<Route, PostgresStore>>, {closure@src/lib.rs:91:38: 91:51}, _>: Service<axum::http::Request<_>>` is not satisfied
   --> src/lib.rs:100:35
    |
100 |     let app = routes::web().layer(session_service).with_state(state);
    |                             ----- ^^^^^^^^^^^^^^^ the trait `Service<axum::http::Request<_>>` is not implemented for `HandleError<tower_cookies::service::CookieManager<SessionManager<Route, PostgresStore>>, {closure@src/lib.rs:91:38: 91:51}, _>`
```

**Comment by maxcountryman** [comment]
Your dependencies are not updated such that the types match.

Without seeing your code, I can guess it's probably axum or http: both need to be updated. L

You will also need to ensure the deletion trait is in scope.

**Comment by HosMercury** [comment]
```
[dependencies]
anyhow = "1.0.75"
argon2 = "0.5.2"
askama = { version = "0.12.1", features = ["serde_json"] }
axum = { version = "0.6.20", features = ["macros"] }
dotenvy = "0.15.7"
dry-run = "0.0.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
regex = "1.10.2"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio-rustls","time","uuid"] }
time = { version = "0.3.30", features = ["serde","macros","formatting"] }
tokio = { version = "1.33.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["fs"] }
tower-sessions = { version = "0.7.0", features = ["postgres-store"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
uuid = { version = "1.5.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
validator = { version = "0.16.1", features = ["derive"] }

```

**Comment by HosMercury** [comment]
there is something missing

**Comment by maxcountryman** [comment]
As I mentioned, axum needs to be updated. You have 0.6.

**Comment by HosMercury** [comment]
`
error[E0599]: no method named `continuously_delete_expired` found for struct `PostgresStore` in the current scope
  --> src/lib.rs:85:14
   |
83 | /         session_store
84 | |             .clone()
85 | |             .continuously_delete_expired(tokio::time::Duration::from...
   | |             -^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `PostgresStore`
   | |_____________|
   |
   `

**Comment by maxcountryman** [comment]
As I said, you need to bring the trait in scope.

Please make sure you follow the examples and give us complete, working examples so we can help you.

**Comment by HosMercury** [comment]
which trait ?

**Comment by rogusdev** [comment]
I also encountered this when upgrading from 0.4. I already had this working with `use tower_sessions::session_store::ExpiredDeletion` however it required the feature `deletion-task` which previously was on `tower-sessions` but was not there anymore, nor moved to `tower-sessions-sqlx-store` so I had to do some digging.

It seems that the missing instruction, which I don't see in any of the docs or git repos, is to add to my cargo toml:
```
tower-sessions-core = { version = "0.10.0", features = ["deletion-task"] }
```

Is this mentioned somewhere that I am missing? There are no complete examples that have this referenced, e.g.
https://github.com/maxcountryman/tower-sessions-stores/blob/main/sqlx-store/examples/postgres.rs

I do see this here -- but I only found it after knowing what to look for, and it was not obvious that this was related:
https://github.com/maxcountryman/tower-sessions-stores/blob/3d60f41bbca0728b95cffeea5922e31704c036a2/sqlx-store/Cargo.toml#L26

Thanks for the great project that clearly takes a lot of work to provide docs for, and the nontrivial improvements that have been made over its lifetime already. Hopefully this is an easy opportunity to clarify things somewhere.

**Comment by maxcountryman** [comment]
The `deletion-task` flag [is enabled by `tower-sessions-sqlx-store`](https://github.com/maxcountryman/tower-sessions-stores/blob/3d60f41bbca0728b95cffeea5922e31704c036a2/sqlx-store/Cargo.toml#L26). What this means is you do not enable it directly anymore and generally speaking on store authors would enable this feature.

This is covered in [the release notes](https://github.com/maxcountryman/tower-sessions/releases/tag/v0.10.0) where we migrate a SQLx example, including the `Cargo.toml` as an example. Generally speaking, the release notes and CHANGELOG are the places folks should be looking when updating breaking releases.

You should not enable `deletion-task` directly and if you find that you have to the most likely explanation is that you're using incompatible versions of `tower-sessions` and `tower-sessions-sqlx-store`.
